-- Tabla de Invitaciones a Workspaces
create table workspace_invitations (
  id bigint generated by default as identity primary key,
  workspace_id bigint references workspaces(id) on delete cascade,
  email text not null,
  role text not null check (role in ('owner', 'collaborator')),
  invited_by uuid not null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamp with time zone default now(),
  expires_at timestamp with time zone default (now() + interval '7 days'),
  metadata jsonb default '{}'::jsonb
);

-- Políticas de seguridad
create policy "Users can view invitations for their workspaces"
  on workspace_invitations for select
  using (exists (
    select 1 from workspace_members 
    where workspace_members.workspace_id = workspace_invitations.workspace_id 
    and workspace_members.user_id = auth.uid()
  ));

create policy "Users can create invitations for their workspaces"
  on workspace_invitations for insert
  with check (exists (
    select 1 from workspace_members 
    where workspace_members.workspace_id = workspace_invitations.workspace_id 
    and workspace_members.user_id = auth.uid()
  ));

create policy "Users can update invitations for their workspaces"
  on workspace_invitations for update
  using (exists (
    select 1 from workspace_members 
    where workspace_members.workspace_id = workspace_invitations.workspace_id 
    and workspace_members.user_id = auth.uid()
  ));

create policy "Users can delete invitations for their workspaces"
  on workspace_invitations for delete
  using (exists (
    select 1 from workspace_members 
    where workspace_members.workspace_id = workspace_invitations.workspace_id 
    and workspace_members.user_id = auth.uid()
  )); 